name: 'Terraform Process Apply'
description: 'Runs Terraform to apply plan'
inputs:
  group:
    description: 'Terraform Group'
    required: true
  github_token:
    description: 'Github Token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Terraform Init
      id: init
      shell: bash
      run: |
        echo "::group::Terraform Init"
        terraform -chdir=./terraform/${{ inputs.group }} init > /dev/null
        echo "::endgroup::"

    - name: Terraform Apply
      id: apply
      shell: bash
      run: |
        echo "::group::Terraform Apply"
        terraform -chdir=./terraform/${{ inputs.group }} apply -no-color -input=false -auto-approve
        echo "::endgroup::"