name: 'Docker Build'
description: 'Reusable Docker Build steps'
inputs:
  aws-account:
    description: 'AWS Account ID'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
    default: us-east-1
  aws-ecr-repo:
    description: 'AWS ECR Repository'
    required: true
  image-tags:
    description: 'Tags to apply to built image'
    default: |
      ${{ inputs.aws-account }}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.aws-ecr-repo }}:${{ env.GITHUB_REF_SLUG }}-latest
      ${{ inputs.aws-account }}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.aws-ecr-repo }}:${{ github.sha }}
  build-args:
    description: 'Docker Build Arguments'

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Build production image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        builder: ${{ steps.buildx.outputs.name }}
        file: Dockerfile
        # Set the desired build target here
        push: true
        build-args: ${{ inputs.build-args }}
        tags: ${{ inputs.image_tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
