name: 'AWS Credentials File'
description: 'Reusable AWS Credentials File creation steps'
inputs:
  aws-account:
    description: 'AWS Account ID'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
    default: us-east-1
  aws-access-key-id-govcloud:
    description: 'AWS GovCloud Access Key ID'
    required: false
  aws-secret-access-key-govcloud:
    description: 'AWS GovCloud Secret Access Key'
    required: false
  aws-govcloud-region:
    description: 'AWS Region'
    required: false
    default: us-gov-east-1
runs:
  using: "composite"
  steps:
    - name: Add profile credentials to ~/.aws/credentials
      shell: bash
      run: |
          aws configure set aws_access_key_id ${{ inputs.aws-access-key-id }} --profile default
          aws configure set aws_secret_access_key ${{ inputs.aws-secret-access-key }} --profile default
          aws configure set default.region ${{ inputs.aws-region }} --profile default

    - name: Add profile credentials to ~/.aws/credentials
      shell: bash
      run: |
        if [ ! -z "${{ inputs.aws-access-key-id-govcloud }}" ] && [ ! -z "${{ inputs.aws-secret-access-key-govcloud }}" ]
        then
          aws configure set aws_access_key_id ${{ inputs.aws-access-key-id-govcloud }} --profile govcloud
          aws configure set aws_secret_access_key ${{ inputs.aws-secret-access-key-govcloud }} --profile govcloud
          aws configure set default.region ${{ inputs.aws-govcloud-region }} --profile govcloud
        fi
