name: 'Terraform Process Plan'
description: 'Runs Terraform to process a plan and creates a comment if action is required'
inputs:
  group:
    description: 'Terraform Group'
    required: true
  github_token:
    description: 'Github Token'
    required: true
runs:
  using: "composite"
  steps:
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform -chdir=./terraform/${{ inputs.group }} init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=./terraform/${{ inputs.group }} validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          set +e
          terraform -chdir=./terraform/${{ inputs.group }} plan -no-color -detailed-exitcode
          echo ::set-output name=exit_status::$?
        continue-on-error: true

      - uses: actions/github-script@v4
        id: query-jobs
        if: github.event_name == 'pull_request' && steps.plan.outputs.exit_status == 2
        with:
          script: |
            const result = await github.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.run_id }},
            });

            return result.data.jobs.find(function(job) { return job.name === "Create a plan for ${{ inputs.group }}" }).id;

      - uses: actions/github-script@v4
        if: github.event_name == 'pull_request' && steps.plan.outputs.exit_status == 2
        with:
          github-token: ${{ inputs.github_token }}
          script: |
            const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
            #### Terraform Plan 📖\`Changes Pending\`

            ${{ format('{0}/checks?check_run_id={1}', github.event.pull_request._links.html.href, steps.query-jobs.outputs.result) }}

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Group: \`${{ inputs.group }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
